name: 'Build Cradio'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      alphas: '["qwerty"]'
      board: '["nice_nano_v2"]'
      shield: '["cradio_left","cradio_right"]'
      custom_config: '["#define MIRYOKU_EXTRA_COLEMAKDH"]'

